env:
  browser: true
  es6: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {
  "quotes": [2, "double"],
  "comma-dangle": ["off"],
  "import/prefer-default-export": ["off"],
  "implicit-arrow-linebreak": ["off"],
  "arrow-parens": ["off"],
  "object-curly-newline": ["off"],
}
